plugins {
    id 'com.android.application'
}

android {
    namespace 'id.my.picoclaw'
    compileSdk 35

    defaultConfig {
        applicationId "id.my.picoclaw"
        minSdk 21
        targetSdk 22
        versionCode 3
        versionName "0.3"

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
